version: "3.5"

services:
  api: 
    container_name: apitask
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongotask
    image: mongo
    ports:
      - "27018:27017"